// Configuration Protocol  © 2026 by Snapshot PB is licensed under CC BY-NC-SA 4.0.
// To view a copy of this license, visit https://creativecommons.org/licenses/by-nc-sa/4.0/

// A profile defining a user configuration for the marker

syntax = "proto3";

package snapshotpb.v1;

import "snapshotpb/v1/autococker.proto";

enum ProfileType {
    PROFILE_TYPE_UNSPECIFIED = 0;
    PROFILE_TYPE_DEFAULT = 1;
    PROFILE_TYPE_CUSTOM = 2;
}

enum ScreenBrightness {
  // Unset / unknown brightness.
  SCREEN_BRIGHTNESS_UNSPECIFIED = 0;

  // Minimal brightness, lowest power consumption.
  SCREEN_BRIGHTNESS_LOW = 1;

  // Default brightness
  SCREEN_BRIGHTNESS_DEFAULT = 2;

  // Maximum brightness, highest power consumption.
  SCREEN_BRIGHTNESS_HIGH = 3;
}

// A profile defining a user configuration for the marker
message Profile {
    // Name for the given profile limited to 10 ASCII characters (0-255)
    string name = 1;

    // Identifier for client to understand granularity of control the user prefers
    ProfileType type = 2;

    // A maximum firerate for the marker. Board-specific timing may be artificially adjusted to honor
    // this cap.
    uint32 fire_rate_cap = 3;

    // The amount of time in minutes for the board to automatically shut off without trigger or button
    // interactions.
    uint32 board_auto_off = 4;

    // Device setting for how bright the screen should be.
    ScreenBrightness screen_brightness = 5;

    // Board-model-specific firing configuration. The set arm identifies the board model.
    oneof board_config {
        AutocockerConfig autococker = 6;
    }
}

message Profiles {
    repeated Profile profiles = 1;
}
